# Use a Node base image
FROM node:latest as build
# build

# Set the working directory to /app (this is the default in the future)
WORKDIR /home

# Install app dependencies
COPY src/frontend/package.json /home/
RUN npm install

# Bundle app source
RUN mkdir -p /home/public
COPY src/frontend/public ./home/public
RUN npm run build

# Serve using a simple HTTP server
FROM nginx:alpine
COPY --from=build /home/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]