FROM continuumio/anaconda3 as build

# Set the working directory to /app (this is the default in the future)
WORKDIR /home

# Install Flask
RUN pip install Flask

# Copy the backend code
COPY src/backend /home

# Set the flask app to run on port 5000
ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0
EXPOSE 5000

CMD ["flask", "run"]